# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'getoptlong'

# Parse CLI arguments.
opts = GetoptLong.new(
  [ '--provider',     GetoptLong::OPTIONAL_ARGUMENT ],
)

provider='virtualbox'
begin
  opts.each do |opt, arg|
    case opt
      when '--provider'
        provider=arg
    end # case
  end # each
  rescue
end

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define :apache, primary: true do |debianbookworm1|
    debianbookworm1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
    end

    debianbookworm1.vm.provider :libvirt do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end
    debianbookworm1.vm.box = "debian/bookworm64"
    debianbookworm1.vm.hostname = "apache"
    debianbookworm1.vm.network :private_network, ip: "192.168.56.11"
    debianbookworm1.vm.provision "shell", inline: <<-SHELL
      apt update
      apt upgrade -y
      apt install -qy git systemd-timesyncd curl gnupg2 openssl apache2
      SHELL
  end

  config.vm.define :wazuh, primary: true do |debianbookworm2|
    debianbookworm2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096", "--cpus", "1"]
    end

    debianbookworm2.vm.provider :libvirt do |lv|
      lv.memory = 4096
      lv.cpus = 1
    end
    debianbookworm2.vm.box = "debian/bookworm64"
    debianbookworm2.vm.hostname = "wazuh"
    debianbookworm2.vm.network :private_network, ip: "192.168.56.12"
    debianbookworm2.vm.provision "shell", inline: <<-SHELL
      apt update
      apt upgrade -y
      apt install -qy git systemd-timesyncd curl gnupg2 openssl docker.io docker-compose
      sysctl -w vm.max_map_count=262144
      git clone https://github.com/wazuh/wazuh-docker.git
      cd wazuh-docker
      git checkout v4.7.2
      cd single-node
      docker-compose -f generate-indexer-certs.yml run --rm generator
      docker-compose -d up
      SHELL
  end

end
